version: 2
updates:
  - package-ecosystem: "pub"
    directory: "packages/socket-client"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "packages/realtime"
    schedule:
      interval: "daily"
