name: realtime
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/SuperViz/realtime-flutter

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  socket_io_client: ^2.0.3+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  faker: ^2.2.0
