name: superviz_socket_client
description: The superviz's realtime package
repository: https://github.com/SuperViz/realtime-flutter/tree/master/packages/realtime
documentation: https://docs.superviz.com/realtime
homepage: https://superviz.com/
issue_tracker: https://github.com/SuperViz/realtime-flutter/issues
topics:
  - realtime
  - superviz

version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  socket_io_client: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  faker: ^2.2.0
  build_runner: ^2.4.13

