name: superviz_socket_client
description: The socket client to superviz dart pakcages
repository: https://github.com/SuperViz/realtime-flutter/tree/master/packages/socket-client
homepage: https://superviz.com/
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  socket_io_client: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  faker: ^2.2.0
  build_runner: ^2.4.13

