name: realtime
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  socket_client:
    path: "../socket-client"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
