name: superviz_realtime
description: The superviz's realtime package
repository: https://github.com/SuperViz/realtime-flutter/tree/master/packages/realtime
documentation: https://docs.superviz.com/realtime
homepage: https://superviz.com/
issue_tracker: https://github.com/SuperViz/realtime-flutter/issues
topics:
  - realtime
  - superviz

publish_to: pub.dev
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2
  superviz_socket_client:
    path: "../socket-client"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
