name: Realtime - Configure and publish package

on:
  push:
    branches: ["master"]
    paths:
      - "packages/realtime/**"
      - ".github/workflows/realtime.ci.yml"

jobs:
  configure-superviz-realtime:
    defaults:
      run:
        working-directory: packages/realtime
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"

      - run: git config --global user.name SuperViz
      - run: git config --global user.email dev@superviz.com

      - name: Install dependencies and run Semantic release
        run: |
          npm install
          npm audit signatures
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    needs: configure-superviz-realtime
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/realtime
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      - run: git pull

      # Setup Dart SDK
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish -f
