name: Realtime - Configure and publish package

on:
  push:
    tags: ["superviz-realtime-[0-9]+.[0-9]+.[0-9]+**"]
  pull_request:
    branches: [master]
    paths:
      - "packages/realtime/**"

jobs:
  configure-superviz-realtime:
    if: ${{ github.event_name == 'pull_request' }}
    defaults:
      run:
        working-directory: packages/realtime
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"

      - run: git config --global user.name SuperViz
      - run: git config --global user.email dev@superviz.com

      - name: Install dependencies and run Semantic release
        run: |
          npm install
          npm audit signatures
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit, push changes, and push tags
        run: |
          git add .
          git commit -m "chore(release): update package versions [skip ci]" || echo "No changes to commit"
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  publish:
    needs: configure-superviz-realtime
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      id-token: write # Required for authentication using OIDC
      pull-requests: write # Required for writing the pull request note
