name: Socket client - Configure and publish pakcage

on:
  push:
    branches: ["master"]
    paths:
      - "packages/socket-client/**"
      - ".github/workflows/socket-client.ci.yml"
      - ".github/workflows/socket-client-publish.ci.yml"

jobs:
  configure_superviz_socket_client:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"

      - run: git config --global user.name SuperViz
      - run: git config --global user.email dev@superviz.com

      - name: Install dependencies and run Semantic release
        run: |
          cd packages/socket-client
          npm install
          npm audit signatures
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): update package versions [skip ci]" || echo "No changes to commit"
          git push --follow-tags

  test:
    needs: configure_superviz_socket_client
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    concurrency: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - run: git config --global user.name SuperViz
      - run: git config --global user.email dev@superviz.com

      - name: Intalling dependencies
        run: |
          cd packages/socket-client
          dart pub get

      - name: Verify formatting
        run: |
          cd packages/socket-client
          dart format --output=write --set-exit-if-changed .

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): format code [skip ci]" || echo "No changes to commit"
          git push --follow-tags

      - name: Running build runner
        run: |
          cd packages/socket-client
          dart run build_runner build

      - name: Analyze project source
        run: |
          cd packages/socket-client
          dart analyze

      - name: Running tests
        run: |
          cd packages/socket-client
          dart test

  publish:
    needs: ["configure_superviz_socket_client", "test"]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    concurrency: publish
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
      working-directory: packages/socket-client
