name: Socket client - Configure pakcage

on:
  push:
    branches: ["master"]
    paths:
      - "packages/socket-client/**"
      - ".github/workflows/socket-client.ci.yml"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  configure_superviz_socket_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: git config --global user.name SuperViz
      - run: git config --global user.email ci@superviz.com

      - run: cd packages/socket-client

      - name: Run npm install
        run: npm install --save-dev semantic-release-pub

      - name: Run Semantic release
        run: npx semantic-release -d
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
