name: Socket client - Configure and publish pakcage

on:
  push:
    branches: ["master"]
    paths:
      - "packages/socket-client/**"
      - ".github/workflows/socket-client.ci.yml"
      - ".github/workflows/socket-client-publish.ci.yml"

jobs:
  configure_superviz_socket_client:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"

      - run: git config --global user.name SuperViz
      - run: git config --global user.email dev@superviz.com

      - name: Install dependencies and run Semantic release
        working-directory: packages/socket-client
        run: |
          npm install
          npm audit signatures
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): update package versions [skip ci]" || echo "No changes to commit"
          git push --tags
          git push

  publish:
    needs: "configure_superviz_socket_client"
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
      working-directory: packages/socket-client
