name: Socket client - Configure pakcage

on:
  push:
    branches: ["master"]
    paths:
      - "packages/socket-client/**"
      - ".github/workflows/socket-client.ci.yml"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  configure_superviz_socket_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=20.8.1"

      - run: git config --global user.name SuperViz
      - run: git config --global user.email ci@superviz.com

      - name: Install dependencies and run Semantic release
        run: |
          cd packages/socket-client
          npm install
          npm audit signatures
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  publish_superviz_socket_client:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - run: git config --global user.name SuperViz
      - run: git config --global user.email ci@superviz.com
      - run: cd packages/socket-client

      - name: Intalling dependencies
        run: dart pub get

      - name: Running build runner
        run: dart run build_runner build

      - name: Analyze project source
        run: dart analyze

      - name: Verify formatting
        run: dart format --output=write --set-exit-if-changed .

      - name: Running build runner
        run: dart run build_runner build

      - name: Running tests
        run: dart test

      - name: Publish
        run: dart pub publish
